name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY_PEM_CONTENT }}" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem
        ssh-keyscan -H 18.234.225.159 >> ~/.ssh/known_hosts

    - name: Get instance IDs
      id: get-instances
      uses: aws-actions/aws-cli-action@v1
      with:
        args: |
          autoscaling describe-auto-scaling-groups --auto-scaling-group-names wp-asg --query 'AutoScalingGroups[0].Instances[*].InstanceId' --output text
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Get public IPs of instances
      id: get-public-ips
      uses: aws-actions/aws-cli-action@v1
      with:
        args: |
          ec2 describe-instances --instance-ids ${{ steps.get-instances.outputs.result }} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Deploy code to instances
      run: |
        for ip in ${{ steps.get-public-ips.outputs.result }}
        do
          echo "Deploying to $ip"
          scp -i ~/.ssh/key.pem -r ./* ubuntu@$ip:/var/www/html/Wordpress/
        done
