name: Deploy WordPress Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KEY_PEM_CONTENT }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Get Auto Scaling Group Instances
        id: get-instances
        run: |
          aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names wp-asg --query 'AutoScalingGroups[0].Instances[*].InstanceId' --output text > instance_ids.txt
          cat instance_ids.txt

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Instance IPs
        run: |
          aws ec2 describe-instances --instance-ids $(cat instance_ids.txt) --query 'Reservations[*].Instances[*].PublicIpAddress' --output text > instance_ips.txt
          cat instance_ips.txt

      - name: Deploy to instances
        run: |
          for ip in $(cat instance_ips.txt); do
            echo "Deploying to $ip"
            scp -r -o StrictHostKeyChecking=no ./* ubuntu@$ip:/var/www/html/Wordpress
            ssh -o StrictHostKeyChecking=no ubuntu@$ip "sudo systemctl restart apache2"
          done

